from googleplaces import GooglePlaces, types, lang

API_KEY = 'AIzaSyBZ6dHIrv_aep5hXWLOnrNvdanTWEHy1EI'

print dir(types)

# google_places = GooglePlaces(API_KEY)
#
# query_result = google_places.nearby_search(
#     location='London, England', keyword='Fish and Chips',
#     radius=20000, types=[
#          types.TYPE_CAFE, types.TYPE_ATM, types.TYPE_HOSPITAL,
#          types.TYPE_STORE, types.TYPE_SHOPPING_MALL,
#          types.TYPE_SCHOOL, types.TYPE_UNIVERSITY
#     ])


['AC_TYPE_ADDDRESS', 'AC_TYPE_CITIES', 'AC_TYPE_ESTABLISHMENT', 'AC_TYPE_GEOCODE', 'AC_TYPE_REGIONS', 'TYPE_ACCOUNTING', 'TYPE_ADMINISTRATIVE_AREA_LEVEL_1', 'TYPE_ADMINISTRATIVE_AREA_LEVEL_2', 'TYPE_ADMINISTRATIVE_AREA_LEVEL_3', 'TYPE_AIRPORT', 'TYPE_AMUSEMENT_PARK', 'TYPE_AQUARIUM', 'TYPE_ART_GALLERY', 'TYPE_ATM', 'TYPE_BAKERY', 'TYPE_BANK', 'TYPE_BAR', 'TYPE_BEAUTY_SALON', 'TYPE_BICYCLE_STORE', 'TYPE_BOOK_STORE', 'TYPE_BOWLING_ALLEY', 'TYPE_BUS_STATION', 'TYPE_CAFE', 'TYPE_CAMPGROUND', 'TYPE_CAR_DEALER', 'TYPE_CAR_RENTAL', 'TYPE_CAR_REPAIR', 'TYPE_CAR_WASH', 'TYPE_CASINO', 'TYPE_CEMETERY', 'TYPE_CHURCH', 'TYPE_CITY_HALL', 'TYPE_CLOTHING_STORE', 'TYPE_COLLOQUIAL_AREA', 'TYPE_CONVENIENCE_STORE', 'TYPE_COUNTRY', 'TYPE_COURTHOUSE', 'TYPE_DENTIST', 'TYPE_DEPARTMENT_STORE', 'TYPE_DOCTOR', 'TYPE_ELECTRICIAN', 'TYPE_ELECTRONICS_STORE', 'TYPE_EMBASSY', 'TYPE_ESTABLISHMENT', 'TYPE_FINANCE', 'TYPE_FIRE_STATION', 'TYPE_FLOOR', 'TYPE_FLORIST', 'TYPE_FOOD', 'TYPE_FUNERAL_HOME', 'TYPE_FURNITURE_STORE', 'TYPE_GAS_STATION', 'TYPE_GENERAL_CONTRACTOR', 'TYPE_GEOCODE', 'TYPE_GROCERY_OR_SUPERMARKET', 'TYPE_GYM', 'TYPE_HAIR_CARE', 'TYPE_HARDWARE_STORE', 'TYPE_HEALTH', 'TYPE_HINDU_TEMPLE', 'TYPE_HOME_GOODS_STORE', 'TYPE_HOSPITAL', 'TYPE_INSURANCE_AGENCY', 'TYPE_INTERSECTION', 'TYPE_JEWELRY_STORE', 'TYPE_LAUNDRY', 'TYPE_LAWYER', 'TYPE_LIBRARY', 'TYPE_LIQUOR_STORE', 'TYPE_LOCALITY', 'TYPE_LOCAL_GOVERNMENT_OFFICE', 'TYPE_LOCKSMITH', 'TYPE_LODGING', 'TYPE_MEAL_DELIVERY', 'TYPE_MEAL_TAKEAWAY', 'TYPE_MOSQUE', 'TYPE_MOVIE_RENTAL', 'TYPE_MOVIE_THEATER', 'TYPE_MOVING_COMPANY', 'TYPE_MUSEUM', 'TYPE_NATURAL_FEATURE', 'TYPE_NEIGHBORHOOD', 'TYPE_NIGHT_CLUB', 'TYPE_PAINTER', 'TYPE_PARK', 'TYPE_PARKING', 'TYPE_PET_STORE', 'TYPE_PHARMACY', 'TYPE_PHYSIOTHERAPIST', 'TYPE_PLACE_OF_WORSHIP', 'TYPE_PLUMBER', 'TYPE_POINT_OF_INTEREST', 'TYPE_POLICE', 'TYPE_POLITICAL', 'TYPE_POSTAL_CODE', 'TYPE_POSTAL_CODE_PREFIX', 'TYPE_POSTAL_TOWN', 'TYPE_POST_BOX', 'TYPE_POST_OFFICE', 'TYPE_PREMISE', 'TYPE_REAL_ESTATE_AGENCY', 'TYPE_RESTAURANT', 'TYPE_ROOFING_CONTRACTOR', 'TYPE_ROOM', 'TYPE_ROUTE', 'TYPE_RV_PARK', 'TYPE_SCHOOL', 'TYPE_SHOE_STORE', 'TYPE_SHOPPING_MALL', 'TYPE_SPA', 'TYPE_STADIUM', 'TYPE_STORAGE', 'TYPE_STORE', 'TYPE_STREET_ADDRESS', 'TYPE_STREET_NUMBER', 'TYPE_SUBLOCALITY', 'TYPE_SUBLOCALITY_LEVEL_1', 'TYPE_SUBLOCALITY_LEVEL_2', 'TYPE_SUBLOCALITY_LEVEL_3', 'TYPE_SUBLOCALITY_LEVEL_4', 'TYPE_SUBLOCALITY_LEVEL_5', 'TYPE_SUBPREMISE', 'TYPE_SUBWAY_STATION', 'TYPE_SYNAGOGUE', 'TYPE_TAXI_STAND', 'TYPE_TRAIN_STATION', 'TYPE_TRANSIT_STATION', 'TYPE_TRAVEL_AGENCY', 'TYPE_UNIVERSITY', 'TYPE_VETERINARY_CARE', 'TYPE_ZOO', '__builtins__', '__doc__', '__file__', '__name__', '__package__']
